import {Interest} from "./interest.model";
import {List} from "immutable";
import {
  musicOptions, sportsOptions, videogamesOptions, tabletopOptions,
  moviesOptions, booksOptions, comicOptions, artsOptions, foodOptions, computersOptions, travelOptions, eventsOptions,
  craftsOptions, natureOptions, homeOptions, fashionOptions, automobileOptions, scienceOptions, moneyOptions,
  newsOptions, spiritualityOptions,
} from "../options/interestOptions.ts";
export const INTERESTS = List<Interest>([
  {
    shortName: 'music',
    name: 'Music',
    title: 'My favorite music is',
    placeholder: 'music',
    options: musicOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'sports',
    name: 'Sports and Physical Activities',
    title: 'My favorite sports and physical activities are',
    placeholder: 'sport',
    options: sportsOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'movies',
    name: 'Movies and Television',
    title: 'My favorite movies and TV series are',
    placeholder: 'movies/TV',
    options: moviesOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'video',
    name: 'Video Games',
    title: 'My favorite video games are',
    placeholder: 'video games',
    options: videogamesOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'tabletop',
    name: 'Tabletop Games',
    title: 'My favorite tabletop games are',
    placeholder: 'tabletop games',
    options: tabletopOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'books',
    name: 'Books and Literature',
    title: 'My favorite books and literature are',
    placeholder: 'favorite books',
    options: booksOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'comic',
    name: 'Comic Books, Manga, and Anime',
    title: 'My favorite Comic Books, Manga, and Anime are',
    placeholder: 'favorite Comic Books',
    options: comicOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'art',
    name: 'Art and Museums',
    title: 'My favorite art and museums are',
    placeholder: 'favorite art and museums',
    options: artsOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'food',
    name: 'Food and Drinks',
    title: 'My favorite food and drinks are',
    placeholder: 'favorite food and drinks',
    options: foodOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'computers',
    name: 'Computers and Electronics',
    title: 'My favorite computers and electronics are',
    placeholder: 'favorite computers and electronics',
    options: computersOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'travel',
    name: 'Travel and Places',
    title: 'My favorite travel and places are',
    placeholder: 'favorite travel and places',
    options: travelOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'events',
    name: 'Social Events',
    title: 'My favorite social events are',
    placeholder: 'favorite social events',
    options: eventsOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'crafts',
    name: 'Arts and Crafts',
    title: 'My favorite arts and crafts are',
    placeholder: 'favorite arts and crafts',
    options: craftsOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'nature',
    name: 'Nature and Outdoors',
    title: 'My favorite nature and outdoors is',
    placeholder: 'favorite nature and outdoors',
    options: natureOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'home',
    name: 'Home and Gardening',
    title: 'My favorite home and gardening is',
    placeholder: 'favorite home and gardening',
    options: homeOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'fashion',
    name: 'Fashion and Beauty',
    title: 'My favorite fashion and beauty is',
    placeholder: 'favorite fashion and beauty',
    options: fashionOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'collectable',
    name: 'Collectable and Memorabilia',
    title: 'My favorite ',
    placeholder: 'favorite collectable or memorabilia',
    options: ["collectable", "memorabilia"],
    removed: false,
    completed: false,
  },
  {
    shortName: 'automobile',
    name: 'Automobiles',
    title: 'My favorite automobiles are',
    placeholder: 'favorite automobiles',
    options: automobileOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'spirituality',
    name: 'Spirituality',
    title: 'My beliefs are',
    placeholder: 'belief',
    options: spiritualityOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'science',
    name: 'Science and Astronomy',
    title: 'My favorite science and Aastronomy is',
    placeholder: 'favorite science and Aatronomy',
    options: scienceOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'money',
    name: 'Money and Finance',
    title: 'My favorite money and finance is',
    placeholder: 'favorite money and finance',
    options: moneyOptions,
    removed: false,
    completed: false,
  },
  {
    shortName: 'news',
    name: 'News and Politics',
    title: 'My favorite news and politics is',
    placeholder: 'favorite news and politics',
    options: newsOptions,
    removed: false,
    completed: false,
  }]);
