import {Option} from '../models/option';

export var languageOptions: Option[] = [
  "Abkhazian",
  "Afar",
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Aymara",
  "Azerbaijani",
  "Bashkir",
  "Basque",
  "Bengali (Bangla",
  "Bhutani",
  "Bihari",
  "Bislama",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Byelorussian (Belarusian",
  "Cambodian",
  "Catalan",
  "Cherokee",
  "Chinese",
  "Chinese (Simplified)	zh",
  "Chinese (Traditional)	zh",
  "Corsican",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Esperanto",
  "Estonian",
  "Faeroese",
  "Farsi",
  "Fiji",
  "Finnish",
  "French",
  "Frisian",
  "Galician",
  "Gaelic (Scottish",
  "Gaelic (Manx",
  "Georgian",
  "German",
  "Greek",
  "Greenlandic",
  "Guarani",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hawaiian",
  "Hebrew	he",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Ido",
  "Indonesian	id",
  "Interlingua",
  "Interlingue",
  "Inuktitut",
  "Inupiak",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kashmiri",
  "Kazakh",
  "Kinyarwanda (Ruanda",
  "Kirghiz",
  "Kirundi (Rundi",
  "Korean",
  "Kurdish",
  "Laothian",
  "Latin",
  "Latvian (Lettish",
  "Limburgish ( Limburger",
  "Lingala",
  "Lithuanian",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Maori",
  "Marathi",
  "Moldavian",
  "Mongolian",
  "Nauru",
  "Nepali",
  "Norwegian",
  "Occitan",
  "Oriya",
  "Oromo (Afaan Oromo",
  "Pashto (Pushto",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Quechua",
  "Rhaeto-Romance",
  "Romanian",
  "Russian",
  "Sami",
  "Sangro",
  "Sanskrit",
  "Serbian",
  "Serbo-Croatian",
  "Sesotho",
  "Setswana",
  "Shona",
  "Sichuan Yi",
  "Sindhi",
  "Sinhalese",
  "Siswati",
  "Slovak",
  "Slovenian",
  "Somali",
  "Spanish",
  "Sundanese",
  "Swahili (Kiswahili",
  "Swedish",
  "Tagalog",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Tonga",
  "Tsonga",
  "Turkish",
  "Turkmen",
  "Twi",
  "Uighur",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Vietnamese",
  "Volapük",
  "Wallon",
  "Welsh",
  "Wolof",
  "Xhosa",
  "Yiddish	yi",
  "Yoruba",
  "Zulu"
  ];
