import {Option} from '../models/option';

export var graduateOptions: Option[] = [
  "Applied Math",
  "Applied Physics",
  "Applied Statistics",
  "Architecture",
  "Bioelectronics",
  "Bioinformatics",
  "Biology",
  "Biomedical Engineering",
  "Biopharmaceutical Engineering",
  "Biostatistics",
  "Business Administration in Management",
  "Business and Information Systems",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Collaborative Doctorate",
  "Computational Biology",
  "Computer Engineering",
  "Computer Science",
  "Computing and Business",
  "Critical Infrastructure Systems",
  "Cyber Security and Privacy",
  "Electrical Engineering",
  "Emergency Management and Business",
  "Engineering Management",
  "Engineering Science",
  "Environmental Engineering",
  "Environmental and Sustainability Policy",
  "Environmental Science",
  "Finance",
  "Healthcare Systems Management",
  "History",
  "Industrial Engineering",
  "Information Systems",
  "Infrastructure Planning",
  "International Business",
  "Internet Engineering",
  "Information Technology and Management",
  "Management of Information Systems",
  "Management of Technology (EMBA)",
  "Management of Technology (MBA)",
  "Manufacturing Systems Engineering",
  "Materials Science and Engineering",
  "Mathematical and Computational Finance",
  "Mathematical Sciences",
  "Mechanical Engineering",
  "Occupational Safety and Health",
  "Pharmaceutical Chemistry",
  "Pharmaceutical Engineering",
  "Pharmaceutical Systems Management",
  "Physics",
  "Power and Energy Systems",
  "Software Engineering",
  "Telecommunications",
  "Transportation",
  "Urban Systems",
];
export var undergraduateOptions: Option[] = [
  "Architecture",
  "Biochemistry",
  "Bioinformatics",
  "Biology",
  "Biomedical Engineering",
  "Biomechanics",
  "Bioinstrumentation",
  "Biomaterials and Tissue Engineering",
  "Biophysics",
  "Business",
  "Accounting",
  "Finance",
  "Innovation and Entrepreneurship",
  "International Business",
  "Management Information Systems",
  "Marketing",
  "Business and Information Systems",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communication and Media",
  "Computer Engineering",
  "Computer Science",
  "Computing and Business",
  "Engineering Science",
  "Engineering Technology",
  "Computer Technology (CPT/CMPT)",
  "Concrete Industry Management (CIMT)",
  "Digital Design",
  "Electrical Engineering",
  "Engineering Science",
  "Mechanical Engineering Technology",
  "Medical Informatics Technology (MIT)",
  "Surveying Engineering Technology",
  "Technology Education (TEED)",
  "Telecommunications Management",
  "Environmental Sciences",
  "History",
  "Human Computer Interaction",
  "Industrial Design",
  "Industrial Engineering",
  "Information Systems",
  "Information Technology",
  "Interior Design",
  "Law, Technology and Culture",
  "Mathematical Sciences",
  "Applied Math",
  "Applied Statistics",
  "Mathematical Biology",
  "Mathematics of Finance and Actuarial",
  "Mechanical Engineering",
  "Patent Law, Technology and Culture",
  "Science, Technology and Culture",
  "Theatre, Arts and Technology",
  "Web and Information Systems",
];
